// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiyIALC9SqWH4XB_biBYTzX6Li9YbRbcE',
    appId: '1:530237795512:web:82e44033a38788f017984d',
    messagingSenderId: '530237795512',
    projectId: 'flutter-firebase-and-riverpod',
    authDomain: 'flutter-firebase-and-riverpod.firebaseapp.com',
    storageBucket: 'flutter-firebase-and-riverpod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEB_1gfZ3InD9jDphhFcrFbqcCx2BYTL8',
    appId: '1:530237795512:android:d02b3e549fb30bfa17984d',
    messagingSenderId: '530237795512',
    projectId: 'flutter-firebase-and-riverpod',
    storageBucket: 'flutter-firebase-and-riverpod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNFurDRRzh6pNOr38u-_FvIdbVsYIxTtg',
    appId: '1:530237795512:ios:6d10974e73b7430e17984d',
    messagingSenderId: '530237795512',
    projectId: 'flutter-firebase-and-riverpod',
    storageBucket: 'flutter-firebase-and-riverpod.appspot.com',
    iosClientId: '530237795512-9vlttda683fc6olg7eohtiofbfle968p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCloudFirestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNFurDRRzh6pNOr38u-_FvIdbVsYIxTtg',
    appId: '1:530237795512:ios:6d10974e73b7430e17984d',
    messagingSenderId: '530237795512',
    projectId: 'flutter-firebase-and-riverpod',
    storageBucket: 'flutter-firebase-and-riverpod.appspot.com',
    iosClientId: '530237795512-9vlttda683fc6olg7eohtiofbfle968p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCloudFirestore',
  );
}
